[style.description]
foreground = "magenta"
underline = false
bold = false
italic = false

[style.command_name]
foreground = "green"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "cyan"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "yellow"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "red"
underline = false
bold = false
italic = true

[display]
compact = false
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720

[directories]
