--#############################################################################
-- Gotham
-- whatyouhide/vim-gotham
-- https://github.com/whatyouhide/vim-gotham
--#############################################################################
-------------------------------------------------------------------------------
-- El tema de color seleccionado será Gotham.
-- The selected colour theme will be Gotham.
--
-- :colorscheme gotham
-------------------------------------------------------------------------------
vim.cmd.colorscheme 'gotham'
-------------------------------------------------------------------------------
--
-------------------------------------------------------------------------------
-- El color del fondo será removido para ser transparente.
-- The background colour will be removed to be transparent.
--
-- :highlight Normal guibg=NONE cterm=NONE
-------------------------------------------------------------------------------
vim.cmd.highlight 'Normal guibg=NONE cterm=NONE'
-------------------------------------------------------------------------------
--#############################################################################
